version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: strawberry-graphql
    versions:
    - 0.45.0
    - 0.45.1
    - 0.45.3
    - 0.45.4
    - 0.47.0
    - 0.48.0
    - 0.48.1
    - 0.48.2
    - 0.48.3
    - 0.49.1
    - 0.50.1
    - 0.51.1
    - 0.52.0
    - 0.52.1
    - 0.53.0
    - 0.53.2
    - 0.54.0
    - 0.56.0
    - 0.56.1
    - 0.56.2
    - 0.56.3
    - 0.57.0
    - 0.57.1
    - 0.57.2
    - 0.57.3
  - dependency-name: alembic
    versions:
    - 1.5.2
    - 1.5.3
    - 1.5.4
    - 1.5.5
    - 1.5.6
    - 1.5.7
  - dependency-name: pytest
    versions:
    - 6.2.2
  - dependency-name: databases
    versions:
    - 0.4.1
    - 0.4.2
  - dependency-name: flake8
    versions:
    - 3.8.4
    - 3.9.0
  - dependency-name: black
    versions:
    - 20.8b1
    - 21.4b0
    - 21.4b1
