"""empty message

Revision ID: 5a8987aaa87b
Revises: e21e9f62c54d
Create Date: 2019-04-19 18:07:56.209130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a8987aaa87b'
down_revision = 'e21e9f62c54d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('edited', sa.DateTime(), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('eye_colors', sa.String(length=250), nullable=True),
    sa.Column('skin_colors', sa.String(length=250), nullable=True),
    sa.Column('hair_colors', sa.String(length=250), nullable=True),
    sa.Column('language', sa.String(length=100), nullable=True),
    sa.Column('average_lifespan', sa.Integer(), nullable=True),
    sa.Column('average_height', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('species')
    # ### end Alembic commands ###
