"""empty message

Revision ID: 7dc26a172a24
Revises: 23f69436a28d
Create Date: 2019-04-22 22:42:32.510722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dc26a172a24'
down_revision = '23f69436a28d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('starships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('edited', sa.DateTime(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('cost_in_credits', sa.String(length=100), nullable=True),
    sa.Column('length', sa.String(length=100), nullable=True),
    sa.Column('max_atmosphering_speed', sa.String(length=100), nullable=True),
    sa.Column('crew', sa.String(length=100), nullable=True),
    sa.Column('passengers', sa.String(length=100), nullable=True),
    sa.Column('cargo_capacity', sa.String(length=100), nullable=True),
    sa.Column('consumables', sa.String(length=100), nullable=True),
    sa.Column('hyperdrive_rating', sa.String(length=100), nullable=True),
    sa.Column('MGLT', sa.String(length=100), nullable=True),
    sa.Column('starship_class', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('starships')
    # ### end Alembic commands ###
